version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - MYSQL_HOST=${MYSQL_HOST:-localhost}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-purabali}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_API_KEYS=${GEMINI_API_KEYS}
      - CACHE_DEFAULT_TTL=${CACHE_DEFAULT_TTL:-3600}
      - CACHE_LOGGING=${CACHE_LOGGING:-INFO}
    volumes:
      - ./cache:/home/appuser/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-purabali}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: 