name: Build and Deploy Docker Image with Version Tag

on:
  push:
    tags:
      - 'v*' # Trigger for tags like v1.0.0, v2.0.0, etc.

env:
  DOCKER_IMAGE: ghcr.io/dhanuprys/purabali-simple-rag
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          echo "Building Docker image with version: $VERSION_TAG"
          docker build -t $DOCKER_IMAGE:$VERSION_TAG .
          docker tag $DOCKER_IMAGE:$VERSION_TAG $DOCKER_IMAGE:latest

      - name: Push Docker Image
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          docker push $DOCKER_IMAGE:$VERSION_TAG
          docker push $DOCKER_IMAGE:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          command_timeout: 20m
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/app/dedan/purabali
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }}
            docker compose pull
            docker compose up --force-recreate -d